/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: 84fe6443722b9260ced2424307b9855a)
interface __BaseEnv_CloudflareEnv {
	SEARCH_RATE_LIMIT_DB: D1Database;
	SEARCH_INDEX: VectorizeIndex;
	SEARCH_ENABLED: "true";
	SEARCH_MIN_SCORE: "0.50";
	OPENAI_EMBEDDING_MODEL: "text-embedding-3-large";
	OPENAI_EMBEDDING_DIMENSIONS: "1536";
	ACECORE_CHAT: Fetcher /* acecore-chat-worker */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
