/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: d95195e3624c262a9d17c88b2fc49ac4)
interface __BaseEnv_CloudflareEnv {
	SEARCH_RATE_LIMIT_DB: D1Database;
	SEARCH_INDEX: VectorizeIndex;
	AI: Ai;
	SEARCH_ENABLED: "true";
	SEARCH_MIN_SCORE: "0.50";
	SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
	SEARCH_EMBEDDING_DIMENSIONS: "1024";
	ACECORE_CHAT: Fetcher /* acecore-chat-worker */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
