/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: c479594af61ea4165856f0e7abdd91d4)
interface __BaseEnv_CloudflareEnv {
	SEARCH_RATE_LIMIT_DB: D1Database;
	SEARCH_INDEX: VectorizeIndex;
	AI: Ai;
	SEARCH_ENABLED: "true";
	CMS_ACCESS_AUD: "57bc3a48647d76bd098cfa1fd2001711ea9ef7e7d98e0343a7e566d6f3426a15";
	CMS_ACCESS_TEAM_DOMAIN: "https://acecore.cloudflareaccess.com";
	CMS_ACCESS_HOSTNAMES: "systems.acecore.net";
	SEARCH_MIN_SCORE: "0.50";
	SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
	SEARCH_EMBEDDING_DIMENSIONS: "1024";
	CMS_AI: Fetcher /* cms-ai */;
	ACECORE_CHAT: Fetcher /* acecore-chat-worker */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
